import type { Metadata } from "next";
import { Press_Start_2P } from "next/font/google";
import "./globals.css";

import CustomSessionProvider from "../components/auth/SessionProvider";
import PixelStyles from "@/components/common/PixelStyles";

const pressStart2P = Press_Start_2P({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-press-start-2p",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pressStart2P.variable} antialiased`}>
        <PixelStyles />
        <CustomSessionProvider>{children}</CustomSessionProvider>
      </body>
    </html>
  );
}
